services:
  - type: worker
    name: amul-stock-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_actual_bot_token_here
      - key: TELEGRAM_CHAT_ID
        value: your_actual_chat_id_here

